name: sar-pipeline
channels:
- conda-forge
- avalentino
- s1-etad
- nodefaults
dependencies:
- affine >=2.4.0
- click >=8.1.8
- geopandas >=1.0.1
- numpy <2.0
- gdal >=3.10.2
- pyproj >=3.7.1
- pyrosar >=0.28.0
- rasterio >=1.4.3
- shapely >=2.0.7
- spatialist >=0.14.0
- s1etad >=0.5.5
- s1etad_tools >=0.8.1
- tomli >=2.2.1
- sentineleof >=0.11.0
- s1reader >=0.2.4
- aioboto3 ==14.1.0
- python >=3.8
- pip
- pip:
  - -e .
  - asf-search>=8.1.1
  - boto3>=1.37.1
  - botocore>=1.37.1
  - h5py>=3.13.0
  - pystac>=1.12.2
  - ruamel-yaml>=0.18.10
  - s1-orbits>=0.1.3
  - cdsetool>=0.2.13
  - dem-handler @ git+https://github.com/GeoscienceAustralia/dem-handler.git@v0.2.2
