name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build tools
        run: pip install build setuptools setuptools_scm wheel

      - name: Build package (generates _version.py)
        run: python -m build --sdist --wheel

      - name: Prepare deployment package
        run: |
          mkdir lambda-deploy
          cp src/lambda_function.py lambda-deploy/
          cp -r sar_pipeline lambda-deploy/

      - name: Install dependencies 
        run: | 
          pip install --target=lambda-deploy \
          asf-search

      - name: Create Zip file for Lambda function
        run: |
          cd lambda-deploy
          zip -r ../code.zip .
          
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:ap-southeast-2:451924316694:function:s1-rtc-check-static-layers-exist \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"