name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Prepare deployment folder
        run: mkdir lambda-deploy

      - name: Install dependencies in Lambda-compatible environment
        uses: addnab/docker-run-action@v3
        with:
          image: public.ecr.aws/lambda/python:3.11
          options: -v ${{ github.workspace }}:/var/task
          run: |
            pip install shapely asf-search boto3 numpy rasterio h5py -t lambda-deploy/

      - name: Copy your code into deployment folder
        run: |
          cp src/lambda_function.py lambda-deploy/
          cp -r sar_pipeline lambda-deploy/

      - name: Zip deployment package
        run: |
          cd lambda-deploy
          zip -r ../code.zip .

      - name: Deploy to AWS Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: lambda update-function-code --function-name arn:aws:lambda:ap-southeast-2:451924316694:function:s1-rtc-check-static-layers-exist --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
